# Generated by Django 5.1 on 2026-04-16 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitors', '0001_initial'),
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('pricing', 'Pricing Change'), ('feature', 'New Feature'), ('content', 'Content Update'), ('design', 'Design Change'), ('new_page', 'New Page'), ('removed', 'Content Removed'), ('other', 'Other')], default='other', max_length=20)),
                ('summary', models.TextField()),
                ('diff_data', models.JSONField(default=dict, help_text='Structured diff: added/removed text blocks, changed elements')),
                ('significance', models.IntegerField(default=5, help_text='1-10 scale of how significant the change is')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='competitors.competitor')),
                ('snapshot_after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_after', to='scraping.snapshot')),
                ('snapshot_before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_before', to='scraping.snapshot')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.TextField(help_text="Claude's strategic analysis of what this change means")),
                ('recommendations', models.JSONField(default=list, help_text='List of actionable recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='intelligence.change')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
