# Generated by Django 5.1 on 2026-04-16 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='screenshots/%Y/%m/%d/')),
                ('html_content', models.TextField(blank=True)),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('status_code', models.IntegerField(null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='competitors.competitor')),
            ],
            options={
                'ordering': ['-captured_at'],
                'get_latest_by': 'captured_at',
            },
        ),
    ]
