# Generated by Django 6.0.4 on 2026-04-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to='screenshots/%Y/%m/%d/'),
        ),
    ]
